/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.yourorghere;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.yourorghere.Transformacion.*;

/**
 *
 * @author jorge
 */
public class JVentana extends javax.swing.JFrame {

    /**
     * Creates new form JVentana
     */
    static boolean traslada = false , rotar = false , escalar = false;
    public JButton trasladar;
    public float x, y, z, grados;

    public JVentana() {

        initComponents();
        botones();
        
        
    }
    
    public void botones(){
        if(traslada == true){
            
            JBrotar.setVisible(false);
            JBescalar.setVisible(false);
            JTgrados.setVisible(false);
            JLgrados.setVisible(false);
            traslada = false;
        }
        
        if(escalar == true){
            
            JBrotar.setVisible(false);
            JBtrasladar.setVisible(false);
            JTgrados.setVisible(false);
            JLgrados.setVisible(false);
            escalar = false;
            
        }
        
         if(rotar == true){
            
            JBescalar.setVisible(false);
            JBtrasladar.setVisible(false);
            JTx.setVisible(false);
            JLx.setVisible(false);
             JTy.setVisible(false);
            JLy.setVisible(false);
            rotar = false;
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JBrotar = new javax.swing.JButton();
        JBescalar = new javax.swing.JButton();
        JBtrasladar = new javax.swing.JButton();
        JLx = new javax.swing.JLabel();
        JLy = new javax.swing.JLabel();
        JLgrados = new javax.swing.JLabel();
        JTx = new javax.swing.JTextField();
        JTgrados = new javax.swing.JTextField();
        JTy = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JBrotar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        JBrotar.setText("Rotar");
        JBrotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBrotarActionPerformed(evt);
            }
        });

        JBescalar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        JBescalar.setText("Escalar");
        JBescalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBescalarActionPerformed(evt);
            }
        });

        JBtrasladar.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        JBtrasladar.setText("Trasladar");
        JBtrasladar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtrasladarActionPerformed(evt);
            }
        });

        JLx.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JLx.setText("X");

        JLy.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JLy.setText("Y");

        JLgrados.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JLgrados.setText("Grados");

        JTx.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JTx.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        JTgrados.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JTgrados.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        JTy.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JTy.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(JLx, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JLy, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTx, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTy, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JLgrados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTgrados, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBrotar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBescalar)
                    .addComponent(JBtrasladar))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLx, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBtrasladar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JTy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBescalar)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBrotar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JLgrados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JTgrados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBrotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBrotarActionPerformed
         try {
            if (JTx.getText() != null && JTy.getText() != null  && JTgrados.getText() != " ") {

                Transformacion.grados = Float.parseFloat(JTgrados.getText());



                Transformacion.indicador = 3;
                this.setVisible(false);
                this.setDefaultCloseOperation(EXIT_ON_CLOSE);
                Transformacion ventana = new Transformacion();
                Transformacion operar = new Transformacion();
                ventana.setResizable(false);
                ventana.setExtendedState(JFrame.MAXIMIZED_BOTH);
                ventana.setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize()));
                ventana.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Inserte todos los campos necesarios");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Inserte solo numeross /n puede ser flotantes o enteros");
        }
    }//GEN-LAST:event_JBrotarActionPerformed

    private void JBescalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBescalarActionPerformed

        try {
            if (JTx.getText() != " " && JTy.getText() != " "  && JTgrados.getText() != null) {

                Transformacion.corX = Float.parseFloat(JTx.getText());

                Transformacion.corY = Float.parseFloat(JTy.getText());

                Transformacion.indicador = 2;
                this.setVisible(false);
                 this.setDefaultCloseOperation(EXIT_ON_CLOSE);
                Transformacion ventana = new Transformacion();
                Transformacion operar = new Transformacion();
                ventana.setResizable(false);
                ventana.setExtendedState(JFrame.MAXIMIZED_BOTH);
                ventana.setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize()));
                ventana.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Inserte todos los campos necesarios");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Inserte solo numeross /n puede ser flotantes o enteros");
        }

    }//GEN-LAST:event_JBescalarActionPerformed

    private void JBtrasladarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtrasladarActionPerformed
        Transformacion trasformacion = new Transformacion();
        try {
            if (JTx.getText() != " " && JTy.getText() != " "  && JTgrados.getText() != null) {

                Transformacion.corX = Float.parseFloat(JTx.getText());
                //trasformacion.setCorX(x);
                Transformacion.corY = Float.parseFloat(JTy.getText());
               
                Transformacion.indicador = 1;
                
                this.setVisible(false);
                 this.setDefaultCloseOperation(EXIT_ON_CLOSE);
                Transformacion ventana = new Transformacion();
                Transformacion operar = new Transformacion();
                ventana.setResizable(false);
                ventana.setExtendedState(JFrame.MAXIMIZED_BOTH);
                ventana.setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize()));
                ventana.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Inserte todos los campos necesarios");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Inserte solo numeross /n puede ser flotantes o enteros");
        }


    }//GEN-LAST:event_JBtrasladarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JVentana().setVisible(true);
            }
        });
        
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBescalar;
    private javax.swing.JButton JBrotar;
    private javax.swing.JButton JBtrasladar;
    private javax.swing.JLabel JLgrados;
    private javax.swing.JLabel JLx;
    private javax.swing.JLabel JLy;
    private javax.swing.JTextField JTgrados;
    private javax.swing.JTextField JTx;
    private javax.swing.JTextField JTy;
    // End of variables declaration//GEN-END:variables
}
